# Generated by Django 6.0.5 on 2026-06-02 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_for_Exam', '0002_myuser_created_at_alter_myuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='model_name',
        ),
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
