# Generated by Django 6.0.5 on 2026-06-03 11:29

import Project_for_Exam.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_for_Exam', '0004_alter_cars_image_path_alter_cars_stock_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveIntegerField(default=Project_for_Exam.models.get_random_rgb, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Red (R)')),
                ('green', models.PositiveIntegerField(default=Project_for_Exam.models.get_random_rgb, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Green (G)')),
                ('blue', models.PositiveIntegerField(default=Project_for_Exam.models.get_random_rgb, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Blue (B)')),
            ],
            options={
                'verbose_name': 'color_palette',
                'verbose_name_plural': 'color_palettes',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='chosen_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project_for_Exam.colorpalette', verbose_name='Chosen color'),
        ),
    ]
