# Generated by Django 6.0.5 on 2026-06-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_for_Exam', '0005_colorpalette_order_address_order_chosen_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
